version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: libros_leysi
      POSTGRES_PASSWORD: leysi
      POSTGRES_DB: db_libros